#!/usr/bin/bash

EXT_MIDI=20:0
INT_MIDI=14:0

song=`basename $1 .txt`

lein run --import-song resources/tabs/$1
lein run

for x in 1 2 3 4 5
do
    aplaymidi --port $EXT_MIDI ../midi/${song}.midi
done

